import { ProductStatus } from '../../products/enums/product-status.enum';

export class SellerProductSalesReportItemDto {
  /**
   * Unique identifier of the seller's product.
   */
  productId: string;

  /**
   * Display name of the seller's product.
   */
  productName: string;

  /**
   * Current lifecycle status of the product.
   */
  productStatus: ProductStatus;

  /**
   * Current selling price of the product.
   *
   * This represents the current product price, while order item prices
   * are stored separately as historical price snapshots.
   */
  unitPrice: string;

  /**
   * Total quantity of this product sold through successful orders.
   */
  totalQuantitySold: number;

  /**
   * Total gross revenue generated by this product.
   *
   * The value is calculated from historical OrderItem prices multiplied
   * by their quantities rather than the current product price.
   */
  totalRevenue: string;

  /**
   * Date and time when the product was created.
   */
  createdAt: string;
}
