import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { User } from '../../users/entities/user.entity';
import { Product } from '../../products/entities/product.entity';
import { Order } from '../../orders/entities/order.entity';
import { Payment } from '../../payments/entities/payment.entity';
import { PaymentStatus } from '../../payments/enums/payment-status.enum';
import { OrderStatus } from '../../orders/enums/order-status.enum';

/**
 * Provides read-only aggregate queries for the dashboard.
 *
 * The dashboard should not load complete users, products, orders,
 * or payments just to calculate summary statistics.
 *
 * Instead, this repository delegates counting and summation
 * to the database through aggregate queries.
 *
 * This keeps the dashboard efficient and prevents unnecessary
 * entity loading and memory usage.
 */
@Injectable()
export class DashboardRepository {
  constructor(
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,

    @InjectRepository(Product)
    private readonly productRepository: Repository<Product>,

    @InjectRepository(Order)
    private readonly orderRepository: Repository<Order>,

    @InjectRepository(Payment)
    private readonly paymentRepository: Repository<Payment>,
  ) {}

  /**
   * Returns the total number of registered users.
   *
   * COUNT is executed directly in the database instead of
   * loading every user entity into application memory.
   */
  async countUsers(): Promise<number> {
    return this.userRepository.count();
  }

  /**
   * Returns the total number of sellers.
   *
   * Seller identification depends on the project's role
   * relationship and will be finalized with the actual
   * User and Role entity structure.
   */
  async countSellers(): Promise<number> {
    return this.userRepository
      .createQueryBuilder('user')
      .innerJoin('user.roles', 'role')
      .where('role.name = :roleName', {
        roleName: 'seller',
      })
      .getCount();
  }

  /**
   * Returns the total number of products.
   *
   * This query currently counts all product records.
   * If the project uses soft deletion, the default TypeORM
   * behavior excludes soft-deleted records.
   */
  async countProducts(): Promise<number> {
    return this.productRepository.count();
  }

  /**
   * Returns the total number of orders.
   */
  async countOrders(): Promise<number> {
    return this.orderRepository.count();
  }

  /**
   * Returns the total number of successful payments.
   *
   * Only payments with SUCCESS status are included.
   * Pending and failed payments are excluded from this metric.
   */
  async countSuccessfulPayments(): Promise<number> {
    return this.paymentRepository.count({
      where: {
        status: PaymentStatus.SUCCESS,
      },
    });
  }

  /**
   * Returns the total revenue generated by paid orders.
   *
   * Revenue is calculated from Order.finalPrice because
   * it represents the final amount charged to the customer
   * after discounts.
   *
   * The database returns decimal values as strings.
   */
  async getTotalRevenue(): Promise<string> {
    const result = await this.orderRepository
      .createQueryBuilder('order')
      .select('COALESCE(SUM(order.finalPrice), 0)', 'totalRevenue')
      .where('order.status = :status', {
        status: OrderStatus.PAID,
      })
      .getRawOne<{ totalRevenue: string }>();

    return result?.totalRevenue ?? '0';
  }

  /**
   * Returns the number of orders waiting for payment.
   *
   * Orders in PENDING_PAYMENT status are included.
   */
  async countPendingPaymentOrders(): Promise<number> {
    return this.orderRepository.count({
      where: {
        status: OrderStatus.PENDING_PAYMENT,
      },
    });
  }
}
