import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { User } from '../../users/entities/user.entity';
import { Product } from '../../products/entities/product.entity';
import { Order } from '../../orders/entities/order.entity';
import { Payment } from '../../payments/entities/payment.entity';
import { PaymentStatus } from '../../payments/enums/payment-status.enum';
import { OrderStatus } from '../../orders/enums/order-status.enum';
import { ProductStatus } from '../../products/enums';
import { SYSTEM_ROLES } from '../../../common/constants/system-roles.constant';

/**
 * Provides read-only aggregate queries for the dashboard.
 *
 * The dashboard should not load complete users, products, orders,
 * or payments just to calculate summary statistics.
 *
 * Instead, this repository delegates counting and summation
 * to the database through aggregate queries.
 *
 * This keeps the dashboard efficient and prevents unnecessary
 * entity loading and memory usage.
 */
@Injectable()
export class DashboardRepository {
  constructor(
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,

    @InjectRepository(Product)
    private readonly productRepository: Repository<Product>,

    @InjectRepository(Order)
    private readonly orderRepository: Repository<Order>,

    @InjectRepository(Payment)
    private readonly paymentRepository: Repository<Payment>,
  ) {}

  /**
   * Returns the total number of registered users.
   *
   * COUNT is executed directly in the database instead of
   * loading every user entity into application memory.
   */
  async countUsers(): Promise<number> {
    return this.userRepository.count();
  }

  /**
   * Returns the total number of users assigned to the seller role.
   *
   * Each user belongs to exactly one role through the User.role
   * ManyToOne relationship. Therefore, the query joins the singular
   * role relation instead of a collection such as user.roles.
   *
   * The role name is filtered in the database so only seller accounts
   * are included in the result.
   */
  async countSellers(): Promise<number> {
    return this.userRepository
      .createQueryBuilder('user')
      .innerJoin('user.role', 'role')
      .where('role.name = :roleName', {
        roleName: SYSTEM_ROLES.SELLER,
      })
      .getCount();
  }

  /**
   * Returns the total number of products.
   *
   * This query currently counts all product records.
   * If the project uses soft deletion, the default TypeORM
   * behavior excludes soft-deleted records.
   */
  async countProducts(): Promise<number> {
    return this.productRepository.count();
  }

  /**
   * Returns the total number of orders.
   */
  async countOrders(): Promise<number> {
    return this.orderRepository.count();
  }

  /**
   * Returns the total number of successful payments.
   *
   * Only payments with SUCCESS status are included.
   * Pending and failed payments are excluded from this metric.
   */
  async countSuccessfulPayments(): Promise<number> {
    return this.paymentRepository.count({
      where: {
        status: PaymentStatus.SUCCESS,
      },
    });
  }

  /**
   * Returns the total revenue generated by paid orders.
   *
   * Revenue is calculated from Order.finalPrice because
   * it represents the final amount charged to the customer
   * after discounts.
   *
   * paidAt is used instead of a single status value so shipped
   * and delivered orders remain included in revenue totals.
   *
   * The database returns decimal values as strings.
   */
  async getTotalRevenue(): Promise<string> {
    const result = await this.orderRepository
      .createQueryBuilder('order')
      .select('COALESCE(SUM(order.finalPrice), 0)', 'totalRevenue')
      .where('order.paidAt IS NOT NULL')
      .getRawOne<{ totalRevenue: string }>();

    return result?.totalRevenue ?? '0';
  }

  /**
   * Returns the number of orders waiting for payment.
   *
   * Orders in PENDING_PAYMENT status are included.
   */
  async countPendingPaymentOrders(): Promise<number> {
    return this.orderRepository.count({
      where: {
        status: OrderStatus.PENDING_PAYMENT,
      },
    });
  }

  /**
   * Returns the number of products owned by a seller.
   *
   * Only products belonging to the specified seller are counted.
   * The query uses a database aggregate instead of loading
   * the seller's complete product collection.
   */
  async countSellerProducts(sellerId: string): Promise<number> {
    return this.productRepository.count({
      where: {
        seller: {
          id: sellerId,
        },
      },
    });
  }

  /**
   * Returns the number of orders containing at least one
   * product owned by the specified seller.
   *
   * DISTINCT is required because one order may contain
   * multiple products belonging to the same seller.
   * Without DISTINCT, such an order would be counted multiple times.
   */
  async countSellerOrders(sellerId: string): Promise<number> {
    const result = await this.orderRepository
      .createQueryBuilder('order')
      .innerJoin('order.items', 'orderItem')
      .innerJoin('orderItem.product', 'product')
      .innerJoin('product.seller', 'seller')
      .where('seller.id = :sellerId', { sellerId })
      .select('COUNT(DISTINCT order.id)', 'count')
      .getRawOne<{ count: string }>();

    return Number(result?.count ?? 0);
  }

  /**
   * Returns the gross revenue generated by the seller's own products
   * in successfully paid orders.
   *
   * Revenue is calculated from OrderItem.unitPrice * quantity.
   * This prevents the seller from receiving the entire Order.finalPrice
   * when an order contains products from multiple sellers.
   *
   * The returned value represents gross item revenue before allocating
   * order-level discounts, shipping fees, taxes, or other order-wide
   * adjustments.
   *
   * A separate business rule must define how order-level discounts
   * are allocated between sellers if net seller revenue is required.
   */
  async getSellerPaidRevenue(sellerId: string): Promise<string> {
    const result = await this.orderRepository
      .createQueryBuilder('order')
      .innerJoin('order.items', 'orderItem')
      .innerJoin('orderItem.product', 'product')
      .innerJoin('product.seller', 'seller')
      .select(
        'COALESCE(SUM(orderItem.unitPrice * orderItem.quantity), 0)',
        'revenue',
      )
      .where('seller.id = :sellerId', { sellerId })
      .andWhere('order.paidAt IS NOT NULL')
      .getRawOne<{ revenue: string }>();

    return result?.revenue ?? '0';
  }

  /**
   * Returns the number of orders containing the seller's products
   * that are still waiting for payment.
   *
   * DISTINCT prevents duplicate counting when an order contains
   * multiple products owned by the same seller.
   */
  async countSellerPendingOrders(sellerId: string): Promise<number> {
    const result = await this.orderRepository
      .createQueryBuilder('order')
      .innerJoin('order.items', 'orderItem')
      .innerJoin('orderItem.product', 'product')
      .innerJoin('product.seller', 'seller')
      .where('seller.id = :sellerId', { sellerId })
      .andWhere('order.status = :status', {
        status: OrderStatus.PENDING_PAYMENT,
      })
      .select('COUNT(DISTINCT order.id)', 'count')
      .getRawOne<{ count: string }>();

    return Number(result?.count ?? 0);
  }

  /**
   * Counts active products whose available inventory is at or below
   * the configured low-stock threshold.
   *
   * Available inventory is calculated by subtracting reserved stock
   * from total stock. Draft and archived products are excluded because
   * they are not currently available in the marketplace.
   */
  async countLowStockProducts(): Promise<number> {
    return this.productRepository
      .createQueryBuilder('product')
      .innerJoin('product.inventory', 'inventory')
      .where('product.status = :status', {
        status: ProductStatus.ACTIVE,
      })
      .andWhere('inventory.stock - inventory.reservedStock <= :threshold', {
        threshold: 5,
      })
      .getCount();
  }

  /**
   * Counts active low-stock products belonging only to the specified seller.
   *
   * The seller filter prevents products owned by other sellers from
   * appearing in the authenticated seller's dashboard.
   *
   * Available inventory is calculated as total stock minus reserved stock.
   */
  async countSellerLowStockProducts(sellerId: string): Promise<number> {
    return this.productRepository
      .createQueryBuilder('product')
      .innerJoin('product.inventory', 'inventory')
      .innerJoin('product.seller', 'seller')
      .where('seller.id = :sellerId', { sellerId })
      .andWhere('product.status = :status', {
        status: ProductStatus.ACTIVE,
      })
      .andWhere('inventory.stock - inventory.reservedStock <= :threshold', {
        threshold: 5,
      })
      .getCount();
  }

  /**
   * Returns aggregated sales data for the admin dashboard.
   *
   * Only paid orders are included because pending or failed
   * orders must not be counted as completed sales.
   *
   * The query groups orders by day or month and calculates
   * both the number of paid orders and their total revenue.
   *
   * The database performs the aggregation directly, so the
   * application does not need to load every order into memory.
   */
  async getAdminSales(
    from?: string,
    to?: string,
    groupBy: 'day' | 'month' = 'day',
  ): Promise<
    {
      period: string;
      ordersCount: number;
      revenue: string;
    }[]
  > {
    /**
     * groupBy is whitelisted before being interpolated into SQL
     * so unexpected client values cannot change the query structure.
     */
    if (groupBy !== 'day' && groupBy !== 'month') {
      throw new BadRequestException('groupBy must be day or month');
    }

    /**
     * PostgreSQL DATE_TRUNC groups timestamps by the requested
     * time unit using the paid_at column so sales analytics follow
     * payment completion rather than order creation.
     *
     * Example:
     * - day   → 2026-08-01
     * - month → 2026-08-01
     *
     * Both values are returned as the beginning of their period.
     */
    const periodExpression = `DATE_TRUNC('${groupBy}', order.paid_at)`;

    const query = this.orderRepository
      .createQueryBuilder('order')
      .select(periodExpression, 'period')
      .addSelect('COUNT(order.id)', 'ordersCount')
      .addSelect('COALESCE(SUM(order.finalPrice), 0)', 'revenue')
      .where('order.paidAt IS NOT NULL');

    /**
     * The date filters are optional.
     *
     * When provided, they limit the aggregation to payments
     * completed within the requested time range.
     */
    if (from) {
      query.andWhere('order.paidAt >= :from', { from });
    }

    if (to) {
      query.andWhere('order.paidAt <= :to', { to });
    }

    const results = await query
      .groupBy(periodExpression)
      .orderBy(periodExpression, 'ASC')
      .getRawMany<{
        period: Date;
        ordersCount: string;
        revenue: string;
      }>();

    return results.map((result) => ({
      /**
       * PostgreSQL may return DATE_TRUNC results as either a Date object
       * or a string depending on the database driver and query result mode.
       *
       * Converting both cases to ISO format keeps the repository response
       * consistent for the service, controller, and API consumers.
       */
      period:
        result.period instanceof Date
          ? result.period.toISOString()
          : new Date(result.period).toISOString(),

      ordersCount: Number(result.ordersCount),
      revenue: result.revenue,
    }));
  }
}
