import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  OneToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { Order } from '../../orders/entities/order.entity';

import { PaymentStatus } from '../enums/payment-status.enum';

/**
 * Payment Entity
 *
 * Represents the payment record associated with an order.
 *
 * Business Rules:
 * - A payment belongs to exactly one order.
 * - An order can have at most one payment.
 * - Only successful payments mark an order as PAID.
 * - Failed payments do not mark an order as PAID.
 * - Payment amount is stored as a monetary snapshot.
 */
@Entity('payments')
export class Payment {
  /**
   * Unique identifier of the payment.
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Order associated with this payment.
   *
   * The unique one-to-one relation ensures
   * that an order can have at most one payment.
   */
  @OneToOne(() => Order, (order) => order.payment, {
    nullable: false,
    onDelete: 'CASCADE',
  })
  @JoinColumn({
    name: 'order_id',
  })
  order: Order;

  /**
   * Unique authority generated by the payment gateway.
   *
   * This value is used to verify the payment result.
   */
  @Column({
    type: 'varchar',
    length: 255,
    nullable: true,
    unique: true,
  })
  authority: string | null;

  /**
   * Transaction identifier returned after
   * a successful payment.
   */
  @Column({
    name: 'transaction_id',
    type: 'varchar',
    length: 255,
    nullable: true,
    unique: true,
  })
  transactionId: string | null;

  /**
   * Payment amount.
   *
   * Stored as a decimal value to preserve
   * monetary precision.
   */
  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
  })
  amount: string;

  /**
   * Current lifecycle status of the payment.
   */
  @Column({
    type: 'enum',
    enum: PaymentStatus,
    default: PaymentStatus.PENDING,
  })
  status: PaymentStatus;

  /**
   * Timestamp when the payment was successfully completed.
   */
  @Column({
    name: 'paid_at',
    type: 'timestamp',
    nullable: true,
  })
  paidAt: Date | null;

  /**
   * Timestamp when the payment record was created.
   */
  @CreateDateColumn({
    name: 'created_at',
  })
  createdAt: Date;

  /**
   * Timestamp when the payment record was last updated.
   */
  @UpdateDateColumn({
    name: 'updated_at',
  })
  updatedAt: Date;
}
