import { Injectable } from '@nestjs/common';

import { InjectRepository } from '@nestjs/typeorm';

import { Repository } from 'typeorm';

import { Payment } from '../entities/payment.entity';

/**
 * Payment Repository
 *
 * Handles database access related to payments.
 *
 * Responsibilities:
 * - Find payments by order ID.
 * - Find payments by gateway authority.
 * - Create payment entities.
 * - Persist payment records.
 *
 * Business logic should remain inside PaymentService.
 */
@Injectable()
export class PaymentRepository {
  constructor(
    @InjectRepository(Payment)
    private readonly repository: Repository<Payment>,
  ) {}

  /**
   * Find a payment associated with a specific order.
   *
   * Each order can have at most one payment record.
   */
  async findByOrderId(orderId: string): Promise<Payment | null> {
    return this.repository.findOne({
      where: {
        order: {
          id: orderId,
        },
      },
      relations: {
        order: true,
      },
    });
  }

  /**
   * Find a payment using the authority
   * generated by the payment gateway.
   *
   * This method is primarily used during
   * payment verification.
   */
  async findByAuthority(authority: string): Promise<Payment | null> {
    return this.repository.findOne({
      where: {
        authority,
      },
      relations: {
        order: true,
      },
    });
  }

  /**
   * Find a payment by its unique identifier.
   */
  async findById(paymentId: string): Promise<Payment | null> {
    return this.repository.findOne({
      where: {
        id: paymentId,
      },
      relations: {
        order: true,
      },
    });
  }

  /**
   * Create a new payment entity.
   *
   * This method only creates the entity in memory.
   * The caller must use save() to persist it.
   */
  create(data: Partial<Payment>): Payment {
    return this.repository.create(data);
  }

  /**
   * Save a payment entity.
   *
   * Used for both creating and updating payments.
   */
  async save(payment: Payment): Promise<Payment> {
    return this.repository.save(payment);
  }
}
