/**
 * Payment Gateway Interface
 *
 * Defines the contract that every payment gateway
 * implementation must follow.
 *
 * Examples:
 * - Zarinpal
 * - Stripe
 * - IDPay
 *
 * PaymentService depends on this abstraction instead
 * of being coupled directly to a specific payment provider.
 */

/**
 * Data required to create a payment request.
 */
export interface CreatePaymentRequest {
  /**
   * Unique identifier of the related order.
   */
  orderId: string;

  /**
   * Payment amount.
   */
  amount: string;

  /**
   * URL where the payment gateway redirects
   * the user after completing the payment process.
   */
  callbackUrl: string;
}

/**
 * Result returned after creating a payment request.
 */
export interface CreatePaymentResponse {
  /**
   * Indicates whether the payment request
   * was successfully created.
   */
  success: boolean;

  /**
   * Unique authority or payment token
   * generated by the payment gateway.
   */
  authority: string | null;

  /**
   * URL where the user must be redirected
   * to complete the payment.
   */
  paymentUrl: string | null;

  /**
   * Error message returned by the gateway
   * when the request fails.
   */
  message: string | null;
}

/**
 * Data required to verify a payment.
 */
export interface VerifyPaymentRequest {
  /**
   * Authority or payment token returned
   * by the payment gateway.
   */
  authority: string;

  /**
   * Expected payment amount.
   */
  amount: string;
}

/**
 * Result returned after verifying a payment.
 */
export interface VerifyPaymentResponse {
  /**
   * Indicates whether the payment
   * was successfully completed.
   */
  success: boolean;

  /**
   * Unique transaction identifier generated
   * after a successful payment.
   */
  transactionId: string | null;

  /**
   * Error message returned by the gateway
   * when payment verification fails.
   */
  message: string | null;
}

/**
 * Payment Gateway Interface
 *
 * Every payment gateway implementation must provide
 * methods for creating and verifying payments.
 */
export interface PaymentGateway {
  /**
   * Create a new payment request.
   */
  createPayment(data: CreatePaymentRequest): Promise<CreatePaymentResponse>;

  /**
   * Verify a completed payment.
   */
  verifyPayment(data: VerifyPaymentRequest): Promise<VerifyPaymentResponse>;
}
