/**
 * Represents one aggregated sales data point
 * in the admin dashboard.
 *
 * The dashboard service will group paid orders
 * by the requested time period.
 */
export class AdminSalesDataPointDto {
  /**
   * Start date of the aggregation period.
   *
   * Examples:
   * - 2026-08-01 for daily grouping
   * - 2026-08-01 for monthly grouping
   */
  period: string;

  /**
   * Number of paid orders in this period.
   */
  ordersCount: number;

  /**
   * Total revenue generated by paid orders
   * in this period.
   *
   * The value is represented as a string
   * because monetary values are stored as decimal values.
   */
  revenue: string;
}

/**
 * Represents the complete sales response
 * returned by the admin dashboard.
 */
export class AdminSalesResponseDto {
  /**
   * Aggregation method used for the response.
   *
   * - day: Group sales by day.
   * - month: Group sales by month.
   */
  groupBy: 'day' | 'month';

  /**
   * Aggregated sales data ordered by period.
   */
  data: AdminSalesDataPointDto[];
}
