import { ApiProperty } from '@nestjs/swagger';

/**
 * Represents the overall statistics displayed
 * on the admin dashboard.
 *
 * This DTO defines the API response contract
 * for high-level business metrics.
 *
 * All values are read-only analytics results.
 * No business data is modified by this DTO.
 */
export class AdminStatisticsResponseDto {
  /**
   * Total number of registered users.
   *
   * Includes all users regardless of their role.
   */
  @ApiProperty({ example: 1200 })
  totalUsers: number;

  /**
   * Total number of registered sellers.
   *
   * This represents users who have the seller role.
   */
  @ApiProperty({ example: 45 })
  totalSellers: number;

  /**
   * Total number of products in the catalog.
   *
   * The exact inclusion of soft-deleted products
   * will be determined by the dashboard query.
   */
  @ApiProperty({ example: 320 })
  totalProducts: number;

  /**
   * Total number of orders in the system.
   */
  @ApiProperty({ example: 890 })
  totalOrders: number;

  /**
   * Total number of successfully completed payments.
   *
   * Pending or failed payments are not included.
   */
  @ApiProperty({ example: 760 })
  totalSuccessfulPayments: number;

  /**
   * Total revenue generated by paid orders.
   *
   * Revenue is calculated from Order.finalPrice,
   * not from pending or failed payments.
   */
  @ApiProperty({ example: '12500000.00' })
  totalRevenue: string;

  /**
   * Number of orders that are still waiting for payment.
   */
  @ApiProperty({ example: 18 })
  pendingPaymentOrders: number;

  /**
   * Number of active products whose available inventory
   * is below the configured low-stock threshold.
   *
   * Available inventory is calculated as:
   * stock - reservedStock.
   */
  @ApiProperty({ example: 12 })
  lowStockProducts: number;
}
