import { ApiProperty } from '@nestjs/swagger';

/**
 * Represents the statistics displayed
 * on a seller's dashboard.
 *
 * All metrics are scoped to the authenticated seller.
 *
 * Seller revenue must only include the seller's own
 * order items, not the entire order finalPrice.
 */
export class SellerDashboardResponseDto {
  /**
   * Number of products owned by the seller.
   */
  @ApiProperty({ example: 12 })
  ownProducts: number;

  /**
   * Number of orders containing at least one
   * product owned by the seller.
   */
  @ApiProperty({ example: 40 })
  ownOrders: number;

  /**
   * Revenue generated by the seller's own products
   * in successfully paid orders.
   *
   * This value must be calculated from the seller's
   * OrderItems using unitPrice * quantity.
   */
  @ApiProperty({ example: '850000.00' })
  ownPaidRevenue: string;

  /**
   * Number of seller orders that are still
   * waiting for payment.
   */
  @ApiProperty({ example: 3 })
  ownPendingOrders: number;

  /**
   * Number of the seller's active products
   * whose available inventory is below
   * the configured low-stock threshold.
   */
  @ApiProperty({ example: 2 })
  ownLowStockProducts: number;
}
